version: '3'
services:
  web:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 3000:3000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  ngrok:
    image: gtriggiano/ngrok-tunnel
    ports:
      - 4040:4040
    environment:
      TARGET_HOST: web
      TARGET_PORT: 3000
    depends_on:
      - web